# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='group',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='im.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='groups',
            field=models.ManyToManyField(blank=True, to='im.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
