# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20161127_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='followrecords',
            name='follow_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.CommunicateType'),
        ),
    ]
