# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20161127_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='followrecords',
            name='record_text',
            field=models.CharField(max_length=80, verbose_name='记录'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=20, verbose_name='地区'),
        ),
    ]
