# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20161128_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrecords',
            name='record_text',
            field=models.CharField(max_length=80, verbose_name=b'\xe8\xae\xb0\xe5\xbd\x95'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\x9c\xb0\xe5\x8c\xba'),
        ),
    ]
