# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 28, 5, 16, 39, 920088, tzinfo=utc), verbose_name='Created Time'),
        ),
    ]
