# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tls', '0002_order_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 1, 1, 27, 39, 494016, tzinfo=utc), verbose_name='Created Time'),
        ),
    ]
