# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='handle',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='room',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
