# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_auto_20170102_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SkuNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Uucode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.ManyToManyField(to='invent.Position')),
            ],
        ),
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='position',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.ManyToManyField(blank=True, to='invent.Contact'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='invent.SkuNo'),
        ),
        migrations.AddField(
            model_name='product',
            name='uucode',
            field=models.ForeignKey(default=b'2017010300512522', max_length=30, on_delete=django.db.models.deletion.CASCADE, to='invent.Uucode'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ManyToManyField(blank=True, to='invent.Warehouse'),
        ),
    ]
