# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0004_auto_20170103_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_time', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='uucode',
            field=models.ForeignKey(default=b'20170103011132010', max_length=30, on_delete=django.db.models.deletion.CASCADE, to='invent.Uucode'),
        ),
        migrations.AddField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.ProductBatch'),
        ),
    ]
