
keys = ['HOMEPATH', 'HTTP_USER_AGENT', 'CONTENT_TYPE', 'USERPROFILE', 'DJANGO_SETTINGS_MODULE', 'PUBLIC', 'HTTP_ACCEPT_ENCODING', 'REMOTE_ADDR', 'OS', 'wsgi.file_wrapper', 'wsgi.version', 'MAIL_USERNAME', 'wsgi.errors', 'PROGRAMW6432', 'CLASSPATH', 'HTTP_ACCEPT', 'FPS_BROWSER_APP_PROFILE_STRING', '_OLD_VIRTUAL_PROMPT', 'CONTENT_LENGTH', 'ANDROID_HOME', 'FLASK_ADMIN', 'COMMONPROGRAMFILES', 'wsgi.multiprocess', 'VBOX_MSI_INSTALL_PATH', 'M2_HOME', 'HTTP_COOKIE', 'PROGRAMFILES', 'COMPUTERNAME', 'COMMANDER_PATH', 'WINDIR', 'APPDATA', 'DOCKER_TOOLBOX_INSTALL_PATH', 'COMMONPROGRAMW6432', 'COMMONPROGRAMFILES(X86)', 'PROGRAMFILES(X86)', 'PATH_INFO', 'FPS_BROWSER_USER_PROFILE_STRING', 'PROCESSOR_ARCHITEW6432', 'MAIL_PASSWORD', 'COMMANDER_INI', 'MAVEN_HOME', 'HTTP_UPGRADE_INSECURE_REQUESTS', 'PSMODULEPATH', 'NUMBER_OF_PROCESSORS', 'QUERY_STRING', 'PROGRAMDATA', 'SERVER_PROTOCOL', 'RUN_MAIN', '#ENVTSLOGTSLOG1608', 'HTTP_CONNECTION', 'CSRF_COOKIE', 'HTTP_HOST', 'PROCESSOR_ARCHITECTURE', 'LOCALAPPDATA', 'TEMP', 'COMSPEC', 'MOZ_PLUGIN_PATH', '#ENVTSLOGSSS1608', 'SERVER_PORT', 'TMP', 'SESSIONNAME', '#ENVTSLOGSHELLEXT5628', 'LOGONSERVER', 'SYSTEMDRIVE', 'wsgi.multithread', 'PATHEXT', 'wsgi.input', 'USERDOMAIN', 'wsgi.url_scheme', 'PHOENIXPATH', 'SYSTEMROOT', 'USERDOMAIN_ROAMINGPROFILE', 'ALLUSERSPROFILE', 'PROCESSOR_LEVEL', 'SCRIPT_NAME', 'PROMPT', '_OLD_VIRTUAL_PATH', 'VIRTUAL_ENV', 'HOMEDRIVE', 'ANDROID_SDK_ROOT', 'COMMANDER_EXE', 'JAVA_HOME', 'SERVER_SOFTWARE', 'SERVER_NAME', 'REQUEST_METHOD', 'ANT_HOME', 'COMMANDER_DRIVE', 'REMOTE_HOST', 'wsgi.run_once', 'PATH', 'HTTP_ACCEPT_LANGUAGE', 'PROCESSOR_IDENTIFIER', 'USERNAME', 'GATEWAY_INTERFACE', 'PROCESSOR_REVISION']
for key in keys:
    print("key:%s" % key)

j = 0

for i in [1,2,3,4]:
    j = j+ i
    print(i,j)


