"""add sex field

Revision ID: 11af500d4aff
Revises: a341ec91ad0d
Create Date: 2016-08-28 22:55:51.603000

"""

# revision identifiers, used by Alembic.
revision = '11af500d4aff'
down_revision = 'a341ec91ad0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    ### end Alembic commands ###
