"""add body_html in Posts table

Revision ID: 529b511a7824
Revises: 119b086e8659
Create Date: 2016-09-01 23:36:19.861000

"""

# revision identifiers, used by Alembic.
revision = '529b511a7824'
down_revision = '119b086e8659'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
