"""add role verification

Revision ID: 77aa4b13ec11
Revises: ebe4594d5c04
Create Date: 2016-08-24 23:38:17.085000

"""

# revision identifiers, used by Alembic.
revision = '77aa4b13ec11'
down_revision = 'ebe4594d5c04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
