"""add user confirmation

Revision ID: 90fd43699781
Revises: 456a945560f6
Create Date: 2016-08-21 20:23:56.938000

"""

# revision identifiers, used by Alembic.
revision = '90fd43699781'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
