"""add comment moderate

Revision ID: dbc867a5e090
Revises: cde6e7e0363a
Create Date: 2016-09-06 22:23:43.852000

"""

# revision identifiers, used by Alembic.
revision = 'dbc867a5e090'
down_revision = 'cde6e7e0363a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    ### end Alembic commands ###
