# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
