# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0005_auto_20161204_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
