# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20161023_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name=b'e-mail'),
        ),
    ]
